'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WcfService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WcfService.ISkyDataService")>  _
    Public Interface ISkyDataService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISkyDataService/DataGetTable", ReplyAction:="http://tempuri.org/ISkyDataService/DataGetTableResponse")>  _
        Function DataGetTable(ByVal sTableName As String, ByVal sSQLText As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISkyDataService/DataGetTable2", ReplyAction:="http://tempuri.org/ISkyDataService/DataGetTable2Response")>  _
        Function DataGetTable2(ByVal sSQLText As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISkyDataService/DataGetCount", ReplyAction:="http://tempuri.org/ISkyDataService/DataGetCountResponse")>  _
        Function DataGetCount(ByVal sTableName As String, ByVal sSQLText As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISkyDataService/GetNowTime", ReplyAction:="http://tempuri.org/ISkyDataService/GetNowTimeResponse")>  _
        Function GetNowTime() As Date
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISkyDataService/DataUpdate", ReplyAction:="http://tempuri.org/ISkyDataService/DataUpdateResponse")>  _
        Sub DataUpdate(ByVal sTableName As String, ByVal sSQLText As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISkyDataService/DataUpdateInByte", ReplyAction:="http://tempuri.org/ISkyDataService/DataUpdateInByteResponse")>  _
        Sub DataUpdateInByte(ByVal sSQLText As String, ByVal Bt() As Byte)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISkyDataService/DataUpdate2", ReplyAction:="http://tempuri.org/ISkyDataService/DataUpdate2Response")>  _
        Sub DataUpdate2(ByVal sSQLText As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISkyDataService/WCFLinkTest", ReplyAction:="http://tempuri.org/ISkyDataService/WCFLinkTestResponse")>  _
        Function WCFLinkTest() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISkyDataService/DataConnectionTest", ReplyAction:="http://tempuri.org/ISkyDataService/DataConnectionTestResponse")>  _
        Function DataConnectionTest() As String
        
        'CODEGEN: 操作 UploadFile 以后生成的消息协定不是 RPC，也不是换行文档。
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISkyDataService/UploadFile", ReplyAction:="http://tempuri.org/ISkyDataService/UploadFileResponse")>  _
        Function UploadFile(ByVal request As WcfService.FileUploadMessage) As WcfService.UploadFileResponse
        
        'CODEGEN: 操作 UploadLargeFile 以后生成的消息协定不是 RPC，也不是换行文档。
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISkyDataService/UploadLargeFile", ReplyAction:="http://tempuri.org/ISkyDataService/UploadLargeFileResponse")>  _
        Function UploadLargeFile(ByVal request As WcfService.FileUploadMessage) As WcfService.UploadLargeFileResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISkyDataService/IfFileExist", ReplyAction:="http://tempuri.org/ISkyDataService/IfFileExistResponse")>  _
        Function IfFileExist(ByVal sSavePath As String, ByVal sFileName As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISkyDataService/DownLoadFile", ReplyAction:="http://tempuri.org/ISkyDataService/DownLoadFileResponse")>  _
        Function DownLoadFile(ByVal sSavePath As String, ByVal sFileName As String) As System.IO.Stream
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISkyDataService/DownLoadLargeFile", ReplyAction:="http://tempuri.org/ISkyDataService/DownLoadLargeFileResponse")>  _
        Function DownLoadLargeFile(ByVal sSavePath As String, ByVal sFileName As String, ByVal nFirID As Integer, ByVal nLength As Integer) As System.IO.Stream
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISkyDataService/DownLoadFileLength", ReplyAction:="http://tempuri.org/ISkyDataService/DownLoadFileLengthResponse")>  _
        Function DownLoadFileLength(ByVal sSavePath As String, ByVal sFileName As String) As Long
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISkyDataService/DeleteFile", ReplyAction:="http://tempuri.org/ISkyDataService/DeleteFileResponse")>  _
        Function DeleteFile(ByVal sSavePath As String, ByVal sFileName As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISkyDataService/RenameFile", ReplyAction:="http://tempuri.org/ISkyDataService/RenameFileResponse")>  _
        Function RenameFile(ByVal sSavePath As String, ByVal sFileName As String, ByVal sNewFileName As String) As String
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="FileUploadMessage", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class FileUploadMessage
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public FileName As String
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public SavePath As String
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public nState As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public FileData As System.IO.Stream
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal FileName As String, ByVal SavePath As String, ByVal nState As Integer, ByVal FileData As System.IO.Stream)
            MyBase.New
            Me.FileName = FileName
            Me.SavePath = SavePath
            Me.nState = nState
            Me.FileData = FileData
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UploadFileResponse
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UploadLargeFileResponse
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ISkyDataServiceChannel
        Inherits WcfService.ISkyDataService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SkyDataServiceClient
        Inherits System.ServiceModel.ClientBase(Of WcfService.ISkyDataService)
        Implements WcfService.ISkyDataService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function DataGetTable(ByVal sTableName As String, ByVal sSQLText As String) As System.Data.DataTable Implements WcfService.ISkyDataService.DataGetTable
            Return MyBase.Channel.DataGetTable(sTableName, sSQLText)
        End Function
        
        Public Function DataGetTable2(ByVal sSQLText As String) As System.Data.DataTable Implements WcfService.ISkyDataService.DataGetTable2
            Return MyBase.Channel.DataGetTable2(sSQLText)
        End Function
        
        Public Function DataGetCount(ByVal sTableName As String, ByVal sSQLText As String) As Integer Implements WcfService.ISkyDataService.DataGetCount
            Return MyBase.Channel.DataGetCount(sTableName, sSQLText)
        End Function
        
        Public Function GetNowTime() As Date Implements WcfService.ISkyDataService.GetNowTime
            Return MyBase.Channel.GetNowTime
        End Function
        
        Public Sub DataUpdate(ByVal sTableName As String, ByVal sSQLText As String) Implements WcfService.ISkyDataService.DataUpdate
            MyBase.Channel.DataUpdate(sTableName, sSQLText)
        End Sub
        
        Public Sub DataUpdateInByte(ByVal sSQLText As String, ByVal Bt() As Byte) Implements WcfService.ISkyDataService.DataUpdateInByte
            MyBase.Channel.DataUpdateInByte(sSQLText, Bt)
        End Sub
        
        Public Sub DataUpdate2(ByVal sSQLText As String) Implements WcfService.ISkyDataService.DataUpdate2
            MyBase.Channel.DataUpdate2(sSQLText)
        End Sub
        
        Public Function WCFLinkTest() As String Implements WcfService.ISkyDataService.WCFLinkTest
            Return MyBase.Channel.WCFLinkTest
        End Function
        
        Public Function DataConnectionTest() As String Implements WcfService.ISkyDataService.DataConnectionTest
            Return MyBase.Channel.DataConnectionTest
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WcfService_ISkyDataService_UploadFile(ByVal request As WcfService.FileUploadMessage) As WcfService.UploadFileResponse Implements WcfService.ISkyDataService.UploadFile
            Return MyBase.Channel.UploadFile(request)
        End Function
        
        Public Sub UploadFile(ByVal FileName As String, ByVal SavePath As String, ByVal nState As Integer, ByVal FileData As System.IO.Stream)
            Dim inValue As WcfService.FileUploadMessage = New WcfService.FileUploadMessage()
            inValue.FileName = FileName
            inValue.SavePath = SavePath
            inValue.nState = nState
            inValue.FileData = FileData
            Dim retVal As WcfService.UploadFileResponse = CType(Me,WcfService.ISkyDataService).UploadFile(inValue)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WcfService_ISkyDataService_UploadLargeFile(ByVal request As WcfService.FileUploadMessage) As WcfService.UploadLargeFileResponse Implements WcfService.ISkyDataService.UploadLargeFile
            Return MyBase.Channel.UploadLargeFile(request)
        End Function
        
        Public Sub UploadLargeFile(ByVal FileName As String, ByVal SavePath As String, ByVal nState As Integer, ByVal FileData As System.IO.Stream)
            Dim inValue As WcfService.FileUploadMessage = New WcfService.FileUploadMessage()
            inValue.FileName = FileName
            inValue.SavePath = SavePath
            inValue.nState = nState
            inValue.FileData = FileData
            Dim retVal As WcfService.UploadLargeFileResponse = CType(Me,WcfService.ISkyDataService).UploadLargeFile(inValue)
        End Sub
        
        Public Function IfFileExist(ByVal sSavePath As String, ByVal sFileName As String) As Boolean Implements WcfService.ISkyDataService.IfFileExist
            Return MyBase.Channel.IfFileExist(sSavePath, sFileName)
        End Function
        
        Public Function DownLoadFile(ByVal sSavePath As String, ByVal sFileName As String) As System.IO.Stream Implements WcfService.ISkyDataService.DownLoadFile
            Return MyBase.Channel.DownLoadFile(sSavePath, sFileName)
        End Function
        
        Public Function DownLoadLargeFile(ByVal sSavePath As String, ByVal sFileName As String, ByVal nFirID As Integer, ByVal nLength As Integer) As System.IO.Stream Implements WcfService.ISkyDataService.DownLoadLargeFile
            Return MyBase.Channel.DownLoadLargeFile(sSavePath, sFileName, nFirID, nLength)
        End Function
        
        Public Function DownLoadFileLength(ByVal sSavePath As String, ByVal sFileName As String) As Long Implements WcfService.ISkyDataService.DownLoadFileLength
            Return MyBase.Channel.DownLoadFileLength(sSavePath, sFileName)
        End Function
        
        Public Function DeleteFile(ByVal sSavePath As String, ByVal sFileName As String) As String Implements WcfService.ISkyDataService.DeleteFile
            Return MyBase.Channel.DeleteFile(sSavePath, sFileName)
        End Function
        
        Public Function RenameFile(ByVal sSavePath As String, ByVal sFileName As String, ByVal sNewFileName As String) As String Implements WcfService.ISkyDataService.RenameFile
            Return MyBase.Channel.RenameFile(sSavePath, sFileName, sNewFileName)
        End Function
    End Class
End Namespace
